### ISSUE TITLE
Zoom Web 1.3.0 isSupportAV  not working correctly

### ISSUE THREAD

**Issue by CSAlanRoman** [zoom/sample-app-web#10]
Hi,

Currently we have  a demo live with Web JS API 1.3.0 and currently isSupportAV is not working correctly.

Here is a demo site we've created for testing this out: https://master.simcita.com/zoom.html

Currently we added a small checkbox where we can toggle isSupportAV. 

Currently if SupportAV is on then the attendee can't see the shared content/camera/PC audio (on chrome)

If SupportAV is off then the attendee can only see what is being shared but not the camera and can't join via PC audio (on chrome)

Please let me know if I can provide more information

**Comment by hrjjml** [comment]
Hi, I work with @CSAlanRoman.
I would like to add that setting isSupportAV to true is working in Edge and Firefox. 
In Chrome, it's displaying black screen. 
See attached screen shots for Chrome and Edge.

![chrome](https://user-images.githubusercontent.com/21371219/44720176-fa3cc080-aa93-11e8-94c6-3ffb301f46fe.png)
![edge](https://user-images.githubusercontent.com/21371219/44720177-fa3cc080-aa93-11e8-9756-516669c5d30d.png)

**Comment by michaelZoomDA** [comment]
Hello @CSAlanRoman, thanks for showing us the bug, we have reported this to out Engineers and they are taking a look to resolve this and update the JS SDK asap.

**Comment by ylkjick532428** [comment]
@CSAlanRoman https://github.com/zoom/sample-app-web/blob/master/index.html we made a preloaded lib to improve the audio and vide cost time when use click join's button. please note the start video button. audio, video and sharing feature works until it turns white.

**Comment by hrjjml** [comment]
@ylkjick532428 I added the preloading of wasm files but I'm still getting the same issue in Chrome.
The issue is that attendee cannot see the what host is sharing and his video, it's just black screen (see attached screen shot). 

We are not interested, for now, with the "Start Video" button 

Please create and start a meeting and try to join using our test page: https://master.simcita.com/zoom.html
It is working properly on Firefox and Edge (although no "Join By Computer" audio button) 


![chrome_after_preload](https://user-images.githubusercontent.com/21371219/44784449-bad9a700-ab5b-11e8-912b-fbbe1af11ca2.png)

**Comment by michaelZoomDA** [comment]
Hi @hrjjml, I was able to test your link on my Mac and iPad. Both times I was able to see the host camera. What version of Chrome are you using? Can you take a screenshot of the host screen as well so that we can see if the proper controls are used?

Host on iPad
![screen shot 2018-08-29 at 9 03 32 am](https://user-images.githubusercontent.com/39344486/44800315-f7f96580-ab6a-11e8-81ed-0cb34b5f0aca.png)
Host on Mac
![screen shot 2018-08-29 at 9 05 26 am](https://user-images.githubusercontent.com/39344486/44800321-faf45600-ab6a-11e8-93f0-edc82570e978.png)

**Comment by CSAlanRoman** [comment]
Hi @michaelZoomDA,

Currently we're using Google Chrome Version 68.0.3440 (Official Build) (64 bit)

![image](https://user-images.githubusercontent.com/42753860/44802024-99db7b00-ab88-11e8-91da-9b5f337ffb75.png)

Below is an image of the chrome browser  followed by the presenter using the app:

![image](https://user-images.githubusercontent.com/42753860/44802095-d14a2780-ab88-11e8-947e-ecf64b4c9a71.png)

![image](https://user-images.githubusercontent.com/42753860/44802179-035b8980-ab89-11e8-96fb-59dcecc9c323.png)

Please let me know if you need more information

**Comment by ylkjick532428** [comment]
@CSAlanRoman I test it. but it also works. can you open the console panel and take a screenshot, if it has an error we can find the root cause and handle it. thanks.

**Comment by hrjjml** [comment]
@ylkjick532428 @michaelZoomDA see attached screen shots of chrome and console. 

![chrome_console](https://user-images.githubusercontent.com/21371219/44855220-99022200-ac38-11e8-900c-189d51d03b9f.png)
![chrome2](https://user-images.githubusercontent.com/21371219/44855221-99022200-ac38-11e8-8405-2dbd48d73d35.png)

**Comment by CSAlanRoman** [comment]
Hi @ylkjick532428,   
Here are the screenshots of me setting it up

Please let me know if you guys require more information:

![001](https://user-images.githubusercontent.com/42753860/44856098-94d70400-ac3a-11e8-857f-63a529e9921e.png)
![002](https://user-images.githubusercontent.com/42753860/44856103-986a8b00-ac3a-11e8-9a89-a451023b69a5.png)

**Comment by CSAlanRoman** [comment]
Hi @michaelZoomDA, @ylkjick532428,

Are there any updates so far for this issue?

**Comment by michaelZoomDA** [comment]
Hi @CSAlanRoman, 
Can you email us at developersupport@zoom.us and we'll set up a quick meeting with your team to help resolve this issue.

**Comment by michaelZoomDA** [comment]
Hey @CSAlanRoman, 
Just following up, looks like there is a Windows issue with Chrome showing the black screen, you either have to reinstall Chrome or disable some plugins. Please refer to the link this link for steps on how to resolve this - https://windowsreport.com/chrome-black-screen-problem-windows-10/
