### ISSUE TITLE
Unable to share video in all browsers except IE11

### ISSUE THREAD

**Issue by tpalmero** [zoom/sample-app-web#9]
I have uploaded the code to my server and started a new meeting. After setting my api key and api secret in the index.js file (Yes, I know you are not supposed to do that but I wanted to run some tests on my private server) I open IE  and join the meeting. I can then share video and see it prefectly in IE 11. However when I do the same thing in  Chrome, Firefox, Opera and Edge I just get a black screen with a green border telling me I am now viewing my screen. Is there an option I need to set to correct this. It says it compatible with Chrome and Firefox but it wont show anything.
<img width="622" alt="zoom1" src="https://user-images.githubusercontent.com/42680983/44600814-1395f200-a7a0-11e8-905d-4dfc48a8bedd.PNG">
<img width="607" alt="zoom2" src="https://user-images.githubusercontent.com/42680983/44600820-1a246980-a7a0-11e8-9190-b685775a953f.PNG">

**Comment by michaelZoomDA** [comment]
Hello @tpalmero we have reported this bug with our Engineers and will followup as soon as they are able to fix the issue.

**Comment by ylkjick532428** [comment]
@tpalmero you will see the block background if a sharing window had been minimized. it can't capture sharing content. check it again whether the situation case block background.

**Comment by michaelZoomDA** [comment]
Hi @tpalmero, Can you post a screenshot of the host's screen and their controls? We're trying to see if the host has the start video controls are enabled. 
Thanks

**Comment by ylkjick532428** [comment]
@tpalmero 
![20180830095514](https://user-images.githubusercontent.com/1235388/44824988-f5fed780-ac3a-11e8-9ce2-5e59130612c4.png) I see this button didn't turn white. 
![20180830095812](https://user-images.githubusercontent.com/1235388/44825046-57bf4180-ac3b-11e8-92d0-16e8d829f8d8.png) like this. some requirements haven't ready. you can open console panel and see whether has a problem. because of some wasm are big. you can preload them [https://github.com/zoom/sample-app-web/blob/master/index.html](https://github.com/zoom/sample-app-web/blob/master/index.html)

**Comment by tpalmero** [comment]
Kudos to @ylkjick532428 and @michaelZoomDA for taking the time to help me solve this issue. Preloading the .wasm files worked perfectly. It gave some errors at first but once I loaded the lib and js files into my var/www/html folder everything fired up and worked perfectly. Thanks for the help! Issue resolved.
